#!/bin/bash -e                                                                                       

source "$(dirname `readlink -f ${0}`)/../release/config"

# the directory that contains framenet.frame.element.map and framenet.original.map
datadir="${SEMAFOR_HOME}/training/data"
# the directory that contains all the lexical unit xmls for FrameNet 1.5
# you can also add your own xmls to this directory
# for format information, take a look at the lu/ directory under the FrameNet release
luxmldir="/mal2/dipanjan/experiments/FramenetParsing/fndata-1.5/lu"
classpath="..:${SEMAFOR_HOME}:${SEMAFOR_HOME}/lib/semafor-deps.jar"
